defaults:
  - cluster: h100
  - checkpoint: uma_sm
  - _self_

benchmark_name: mp-binary-pbe-elasticity

job:
  run_name: ${checkpoint.model_name}
  run_dir: ${cluster.run_dir}
  device_type: ${cluster.device}
  debug: ${cluster.debug}
  scheduler:
    mode: ${cluster.mode}
    distributed_init_method: FILE
    num_array_jobs: 500
    slurm:
      account: ${cluster.account}
      qos: ${cluster.qos}
      partition: ${cluster.partition}
      mem_gb: ${cluster.mem_gb}
      timeout_hr: 72
  logger:
    _target_: fairchem.core.common.logger.WandBSingletonLogger.init_wandb
    _partial_: true
    entity: fairchem
    project: uma-benchmarks
    group: ${checkpoint.model_name}
    job_type: ${benchmark_name}

runner:
  _target_: fairchem.core.components.calculate.elasticity_runner.ElasticityRunner
  calculator:
    _target_: fairchem.core.calculate.ase_calculator.FAIRChemCalculator
    predict_unit:
      _target_: fairchem.core.units.mlip_unit.load_predict_unit
      path: ${checkpoint.ckpt_path}
  task_name: omat
  input_data:
    _target_: fairchem.core.datasets.ase_datasets.AseDBDataset
    config:
      src: ${cluster.data_root_dir}/materials/mp-elasticity/mp-binary-pbe-elasticity-2025.1.aselmdb

reducer:
  _target_: fairchem.core.components.benchmark.benchmark_reducer.JsonDFReducer
  target_data_path: ${cluster.data_root_dir}/materials/mp-elasticity/mp-binary-pbe-elasticity-2025.1.json.gz
  benchmark_name: ${benchmark_name}
  index_name: mp_id
