"""
Copyright (c) Meta Platforms, Inc. and affiliates.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.

Genarris Output Processing and Initial Deduplication Module

This module handles the complete processing pipeline for raw Genarris structure generation
outputs, converting them into standardized formats suitable for ML-based relaxation and
analysis. It implements the critical bridge between structure generation and optimization.

Key Features:
- Efficient parsing of Genarris JSON output files with structure and energy data
- Conversion to standardized Parquet format for high-performance data access
- Initial structure deduplication to remove obvious duplicates before expensive ML relaxation
- Distributed processing support with partitioning for parallel execution

Processing Pipeline:
1. Raw Data Parsing: Extract structures and metadata from Genarris JSON files
2. Format Conversion: Convert to CIF strings and structured data records
3. Initial Filtering: Remove structures with obvious defects or unrealistic properties
4. Pre-relaxation Deduplication: Eliminate duplicate structures using crystallographic comparison
5. Partitioning: Distribute structures across partitions for efficient parallel processing
6. Parquet Export: Save processed data in optimized columnar format
"""

from __future__ import annotations

import os
from typing import TYPE_CHECKING, Any

import pandas as pd
from ase.io.jsonio import decode
from fairchem.applications.fastcsp.core.utils.deduplicate import deduplicate_structures
from fairchem.applications.fastcsp.core.utils.logging import get_central_logger
from fairchem.applications.fastcsp.core.utils.slurm import (
    get_process_slurm_config,
    submit_slurm_jobs,
)
from fairchem.applications.fastcsp.core.utils.structure import (
    check_correct_z,
    check_molecule_matches_reference,
    get_partition_id,
    load_reference_graph,
)
from p_tqdm import p_map
from pymatgen.io.ase import AseAtomsAdaptor
from pymatgen.io.cif import CifWriter
from tqdm import tqdm

if TYPE_CHECKING:
    from pathlib import Path

    import networkx as nx


def get_pre_relax_filter_config(config: dict[str, Any]) -> dict[str, Any]:
    """
    Extract and validate pre-relaxation filtering parameters from workflow configuration.

    This function processes configuration parameters that control the initial deduplication
    and filtering of structures generated by Genarris before they undergo expensive ML
    relaxation.

    Args:
        config: Complete workflow configuration dictionary

    Returns:
        dict: Pre-relaxation filtering parameters containing:
            - ltol: Lattice parameter tolerance for structure matching (default: 0.2)
            - stol: Site position tolerance for structure matching (default: 0.3)
            - angle_tol: Lattice angle tolerance in degrees (default: 5.0)
            - density_bin_size: Density blocker bin (g/cc) for hash grouping (default: None)
            - npartitions: Number of partitions for parallel processing (default: 1)

    Configuration Guidelines:
        - Stricter tolerances (lower ltol/stol) preserve more unique structures
        - Smaller density_bin_size creates more, smaller buckets -> faster dedup
          but may miss duplicates whose density falls across bin boundaries
        - Higher npartitions improves parallelization for large datasets
        - Parameters should be consistent with post-relaxation filtering for continuity

    Notes:
        - Pre-relaxation filtering uses looser tolerances than post-relaxation
        - Conservative filtering prevents loss of potentially important polymorphs
        - Partitioning strategy affects memory usage and parallel efficiency
    """
    match_config = config.get("pre_relaxation_filter", {})
    return {
        "remove_problematic": match_config.get(
            "remove_problematic", False
        ),  # default keep problematic structures (matches post_relaxation_filter)
        "assign_groups": match_config.get(
            "assign_groups", False
        ),  # default assign group indices to similar structures
        "remove_duplicates": match_config.get("remove_duplicates", False),
        "ltol": match_config.get("ltol", 0.2),  # default lattice tolerance
        "stol": match_config.get("stol", 0.3),  # default site tolerance
        "angle_tol": match_config.get(
            "angle_tol", 5
        ),  # default angle tolerance in degrees
        "density_bin_size": match_config.get(
            "density_bin_size", None
        ),  # default density blocker bin (g/cc)
        "density_tol": match_config.get(
            "density_tol", None
        ),  # g/cc; cheap |Δρ| prefilter before sm.fit. None = off.
        "bin_by_conf": match_config.get(
            "bin_by_conf", False
        ),  # include conf_id in the dedup bin key
        "bin_by_z": match_config.get(
            "bin_by_z", False
        ),  # include Z in the dedup bin key
        "bin_by_spg": match_config.get(
            "bin_by_spg", False
        ),  # include spg_generated in the dedup bin key
        "apply_niggli_filter": match_config.get(
            "apply_niggli_filter", False
        ),  # Whether to apply a fast Niggli cell filter before the full StructureMatcher
        "npartitions": match_config.get(
            "npartitions", 1
        ),  # default number of partitions
    }


def structure_to_row(
    hash_id: str,
    struct_dict: dict,
    mol_id: str,
    conf_id: str,
    z_val: int,
    npartitions: int = 1000,
    reference_graph: nx.Graph | None = None,
) -> dict:
    """
    Convert structure data to standardized DataFrame row format.
            - mol_id: Molecule identifier
            - conf_id: Conformer identifier
            - z: Number of formula units per unit cell
            - spg_generated: Space group number
            - structure_id: Unique structure identifier
            - formula: Reduced chemical formula
            - n_atoms: Total number of atoms in unit cell
            - volume: Unit cell volume in Ų
            - cif: Crystal structure in CIF format
            - partition_id: Partition assignment for parallel processing
            - structure: Pymatgen Structure object for analysis

    Processing Steps:
        1. Decode ASE JSON format to Atoms object
        2. Convert to pymatgen Structure for analysis
        3. Extract chemical composition and geometric properties
        4. Generate CIF string representation
        5. Assign consistent partition ID for distributed processing
    """
    atoms = struct_dict
    structure = AseAtomsAdaptor.get_structure(atoms)
    formula = structure.composition.reduced_formula
    n_atoms = len(structure)
    volume = structure.volume
    density = structure.density
    # CifWriter(symprec=None, refine_struct=False) skips the per-structure
    # symmetry analysis that dominates structure.to(fmt="cif") runtime.
    cif_str = str(CifWriter(structure, symprec=None, refine_struct=False))
    spg = int(atoms.info["spg"])
    unique_structure_id = (
        f"mol={mol_id}::conf={conf_id}::z={z_val}::spg={spg}::hash={hash_id}"
    )

    return {
        "mol_id": mol_id,
        "conf_id": conf_id,
        "z": z_val,
        "structure_id": unique_structure_id,
        "formula": formula,
        "n_atoms": n_atoms,
        "spg_generated": spg,
        "density_generated": density,
        "volume_generated": volume,
        "cif_generated": cif_str,
        "partition_id": get_partition_id(unique_structure_id, npartitions),
        "structure_generated": structure,
        "validity.crystal_generated.correct_z": check_correct_z(structure, z_val),
        "validity.crystal_generated.molecule_matches_reference": check_molecule_matches_reference(
            structure, reference_graph
        ),
    }


def process_genarris_outputs_single(
    input_dir: Path,
    output_dir: Path,
    remove_problematic: bool = False,
    remove_duplicates: bool = False,
    ltol: float = 0.3,
    stol: float = 0.4,
    angle_tol: float = 5,
    bin_by_conf: bool = False,
    bin_by_z: bool = False,
    bin_by_spg: bool = False,
    density_bin_size: float | None = None,
    apply_niggli_filter: bool = False,
    npartitions: int = 1000,
    assign_groups: bool = True,
    density_tol: float | None = None,
):
    """
    Process Genarris output files for a single (mol_id, conf_id) directory.

    Converts raw Genarris JSON structure files into standardized parquet format
    with structure deduplication and metadata extraction. The directory may
    contain multiple Z subdirectories; each ``structures.json`` is parsed and
    Z is read from the directory hierarchy.

    Args:
        input_dir: Conformer-level directory.
                 Expected: <mol_id>/<conf_id>/<z>/symm_rigid_press/structures.json
                 or fallback <mol_id>/<conf_id>/<z>/structures.json.
                 mol_id and conf_id are read from input_dir's path:
                 conf_id = input_dir.name, mol_id = input_dir.parent.name.
        output_dir: Where processed parquet files are saved.
        remove_duplicates: Whether to drop duplicates (default: False).
        ltol, stol, angle_tol: StructureMatcher tolerances.
        density_bin_size: Density blocker bin (g/cc) for hash grouping (default: None).
        npartitions: Number of partitions for downstream parallel processing.
        assign_groups: Whether to run the dedup blocker + group assignment.
    """
    logger = get_central_logger()
    # Use all CPUs allocated to this SLURM task at runtime
    num_cpus = max(len(os.sched_getaffinity(0)), 1)
    # input_dir is the conformer-level directory: .../<mol_id>/<conf_id>
    conf_id = input_dir.name
    reference_graph = load_reference_graph(input_dir, conf_id)
    mol_id = input_dir.parent.name
    logger.info(f"Processing {input_dir} (mol_id={mol_id}, conf_id={conf_id})")

    # The Niggli (a,b,c,alpha,beta,gamma) prefilter is only well-defined
    # *within* a fixed-composition bucket. Outside (mol_id, Z, spg) it can
    # incorrectly drop legitimate matches whose Niggli reductions disagree
    # because of differing Z or symmetry.
    if apply_niggli_filter and not (bin_by_z and bin_by_spg):
        logger.warning(
            "apply_niggli_filter=True is most reliable inside a "
            "(mol_id, Z, spg) bucket. Got bin_by_z=%s, bin_by_spg=%s; "
            "results may be sensitive to (ltol, angle_tol). Set both "
            "bin_by_z=True and bin_by_spg=True to silence this warning.",
            bin_by_z,
            bin_by_spg,
        )
    # Sort so two runs over the same directory produce the same row order
    # (Path.glob returns filesystem order, which is not deterministic).
    json_files = sorted(input_dir.glob("*/structures/symm_rigid_press/structures.json"))
    generation_method = "genarris"
    # in case Genarris version is different
    # or other structure generation method is used
    if not json_files:
        json_files = sorted(input_dir.rglob("structures.json"))
        generation_method = "other"
    logger.info(f"Found {len(json_files)} files / {input_dir}")

    # Pass 1: enumerate (hash_id, struct_dict, z_val) items across all JSON files.
    all_items: list[tuple[str, dict, int]] = []
    for file_path in tqdm(json_files, desc="Reading files"):
        try:
            json_file_parents = list(file_path.parents)
            if generation_method == "genarris":
                # based on expected directory structure
                # <z>/symm_rigid_press/structures.json
                # parents: [0]=symm_rigid_press, [1]=structures, [2]=z
                z_dir = json_file_parents[2]
            else:
                # based on expected directory structure
                # <z>/structures.json
                # parents: [0]=<z>
                z_dir = json_file_parents[0]
            z_val = int(z_dir.name)
        except (ValueError, IndexError) as e:
            logger.warning(f"Failed to extract Z from path {file_path}: {e}")
            continue

        try:
            with file_path.open("r") as f:
                struct_data = decode(f.read())
        except Exception as e:
            logger.warning(f"Failed to read {file_path}: {e}")
            continue

        for hash_id, struct_dict in struct_data.items():
            all_items.append((hash_id, struct_dict, z_val))

    if not all_items:
        logger.warning(f"No structures found in {input_dir}")
        return

    # Pass 2: parallel structure_to_row conversion. ``reference_graph`` is
    # threaded through so the generation-time validity flags (correct_z,
    # molecule_matches_reference) are computed in-worker.
    def _convert(item):
        hash_id, struct_dict, z_val = item
        try:
            return structure_to_row(
                hash_id,
                struct_dict,
                mol_id,
                conf_id,
                z_val,
                npartitions,
                reference_graph=reference_graph,
            )
        except Exception as e:
            logger.warning(f"Failed to convert structure {hash_id} in {input_dir}: {e}")
            return None

    rows = p_map(
        _convert,
        all_items,
        num_cpus=num_cpus,
        desc="Converting structures",
    )
    all_rows = [r for r in rows if r is not None]

    structures_df = pd.DataFrame(all_rows)

    # Separate structures that failed the generation-time validity checks.
    valid_mask = (
        structures_df["validity.crystal_generated.correct_z"]
        & structures_df["validity.crystal_generated.molecule_matches_reference"]
    )
    problematic_structures_df = structures_df[~valid_mask]
    structures_df_filtered = structures_df[valid_mask]
    logger.info(
        f"Pre-relax validity split for {input_dir}: "
        f"{len(structures_df_filtered)} valid / {len(problematic_structures_df)} problematic "
        f"(of {len(structures_df)} total)"
    )

    if assign_groups and not structures_df_filtered.empty:
        # Pre-relax dedup blocker = (mol_id, Z, conf_id, spg_generated,
        # density-bin @ density_bin_size). Representative per group = row
        # whose density_generated is closest to the group median (robust to
        # high-density packing artefacts).
        structures_df_filtered = deduplicate_structures(
            structures_df_filtered,
            structure_col="structure_generated",
            conf_col="conf_id" if bin_by_conf else None,
            z_col="z" if bin_by_z else None,
            spg_col="spg_generated" if bin_by_spg else None,
            density_col="density_generated",
            density_bin_size=density_bin_size,
            ltol=ltol,
            stol=stol,
            angle_tol=angle_tol,
            ignored_species=["H"],
            density_tol=density_tol,
            apply_niggli_filter=apply_niggli_filter,
            scale=not bin_by_z,
            primitive_cell=not bin_by_z,
            keep="median" if remove_duplicates else None,
            keep_col="density_generated",
            n_jobs=num_cpus,
        )
    if assign_groups:
        problematic_structures_df["group_index"] = (
            "-1"  # Mark problematic structures with group "-1" (string to match
        )
        #         deduplicate_structures' f"{hash}_{subgroup}" dtype)

    if not remove_problematic:
        # Reintegrate problematic structures if not removing them
        logger.info("Reintegrating problematic structures")
        structures_df = pd.concat(
            [structures_df_filtered, problematic_structures_df], ignore_index=True
        )
    else:
        structures_df = structures_df_filtered
    structures_df = structures_df.drop(columns=["structure_generated"])
    structures_df.to_parquet(
        output_dir,
        compression="zstd",
        partition_cols=["partition_id"],
    )
    logger.debug(f"Saved {len(structures_df)} structures to {output_dir}")


def process_genarris_outputs(
    input_dir: Path,
    output_dir: Path,
    pre_relax_config: dict[str, Any],
    remove_problematic: bool = False,
    remove_duplicates: bool = False,
    ltol: float = 0.2,
    stol: float = 0.3,
    angle_tol: float = 5,
    bin_by_conf: bool = False,
    bin_by_z: bool = False,
    bin_by_spg: bool = False,
    apply_niggli_filter: bool = False,
    density_bin_size: float | None = None,
    npartitions: int = 1000,
    assign_groups: bool = True,
    density_tol: float | None = None,
):
    """
    Batch process multiple Genarris output directories using SLURM parallel execution.

    Args:
        input_dir: Root directory containing multiple molecule directories
        output_dir: Output directory where processed results will be saved
        pre_relax_config: Configuration dictionary containing SLURM and processing parameters
        remove_problematic: Whether to drop structures that failed the generation-time
                            validity checks before deduplication (default: False)
        remove_duplicates: Whether to perform deduplication (default: False)
        ltol: Lattice parameter tolerance for structure deduplication
        stol: Site tolerance for structure deduplication
        angle_tol: Angle tolerance for structure deduplication
        density_bin_size: Density blocker bin (g/cc) for hash grouping (default: None)
        npartitions: Number of partitions for distributed processing

    Returns:
        List of submitit job objects for monitoring execution status
    """
    logger = get_central_logger()

    # Get SLURM configuration
    slurm_params = get_process_slurm_config(pre_relax_config)

    job_args = []
    for mol_dir in input_dir.iterdir():
        if not mol_dir.is_dir():
            continue
        for conf_dir in mol_dir.iterdir():
            if not conf_dir.is_dir():
                continue
            processed_dir = output_dir / mol_dir.name / conf_dir.name

            if (
                processed_dir.exists()
                and len(list(processed_dir.glob("*/*.parquet"))) > 0
            ):
                logger.info(
                    f"Skipping {conf_dir} because {processed_dir} already exists"
                )
                continue

            job_args.append(
                (
                    process_genarris_outputs_single,
                    (conf_dir, processed_dir),
                    {
                        "remove_duplicates": remove_duplicates,
                        "remove_problematic": remove_problematic,
                        "ltol": ltol,
                        "stol": stol,
                        "angle_tol": angle_tol,
                        "bin_by_conf": bin_by_conf,
                        "bin_by_z": bin_by_z,
                        "bin_by_spg": bin_by_spg,
                        "density_bin_size": density_bin_size,
                        "apply_niggli_filter": apply_niggli_filter,
                        "npartitions": npartitions,
                        "assign_groups": assign_groups,
                        "density_tol": density_tol,
                    },
                )
            )

    return submit_slurm_jobs(
        job_args,
        output_dir=output_dir.parent / "slurm",
        **slurm_params,
    )
