model: escnmd_backbone_lr
max_num_elements: 100
sphere_channels: 16
lmax: 2
mmax: 2
use_pbc: False
use_pbc_single: False
edge_channels: 16
distance_function: gaussian
num_distance_basis: 16
regress_forces: True
regress_stress: False
direct_forces: True
num_layers: 2
hidden_channels: 16
norm_type: rms_norm_sh
act_type: gate
ff_type: spectral
chg_spin_emb_type: "rand_emb"
cs_emb_grad: True
dataset_list: ${dataset_list}


hidden_channels_lr: 16
heisenberg_tf: False
latent_charge_tf: true
otf_graph: True
cutoff_lr: 15.0
lr_output_scaling_factor: 1.0
normalize_charges_tf: False
equil_charges_tf: False
use_ewald_tf: True